import{a as y,S as p,i as b}from"./assets/vendor-b11e2a50.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const L="44405907-01ac5a46b548f68b2a274235a",w="https://pixabay.com/api/",v=15;async function f(e,r=1){const s=`${w}?key=${L}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${v}`;try{return(await y.get(s)).data}catch(n){throw console.error("Error fetching the images:",n),n}}function P(e){e.innerHTML=""}function m(e,r){const s=e.map(t=>`
        <a href="${t.largeImageURL}" class="gallery__item">
            <img src="${t.webformatURL}" alt="${t.tags}" class="gallery__image" />
            <div class="info">
                <p class="info-item"><b>Likes:</b> ${t.likes}</p>
                <p class="info-item"><b>Views:</b> ${t.views}</p>
                <p class="info-item"><b>Comments:</b> ${t.comments}</p>
                <p class="info-item"><b>Downloads:</b> ${t.downloads}</p>
            </div>
        </a>
    `).join("");r.insertAdjacentHTML("beforeend",s),new p(".gallery a").refresh()}function i(e,r){b[e]({title:e.charAt(0).toUpperCase()+e.slice(1),message:r})}function c(e){const r=document.querySelector(".load-more");e?r.classList.remove("hidden"):r.classList.add("hidden")}function S(){const{height:e}=document.querySelector(".gallery__item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}const $=document.getElementById("searchForm"),E=document.getElementById("searchQuery"),l=document.getElementById("results"),I=document.querySelector(".load-more");let a=1,h="";$.addEventListener("submit",async e=>{e.preventDefault();const r=E.value.trim();if(!r){i("error","Search query cannot be empty");return}h=r,a=1,P(l),c(!1),g();try{const{hits:s,totalHits:n}=await f(r,a);d(),s.length>0?(m(s,l),c(a*15<n)):i("info","Sorry, there are no images matching your search query. Please try again!")}catch{d(),i("error","Something went wrong. Please try again later.")}});I.addEventListener("click",async()=>{a++,g();try{const{hits:e,totalHits:r}=await f(h,a);d(),e.length>0&&(m(e,l),S(),c(a*15<r)),a*15>=r,i("info","We're sorry, but you've reached the end of search results."),c(!1)}catch{d(),i("error","Something went wrong. Please try again later.")}});function g(){l.insertAdjacentHTML("beforeend",'<div class="loader"></div>')}function d(){const e=document.querySelector(".loader");e&&e.remove()}
//# sourceMappingURL=commonHelpers.js.map
