import{a as y,S as p,i as b}from"./assets/vendor-b11e2a50.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const w="44405907-01ac5a46b548f68b2a274235a",L="https://pixabay.com/api/",v=15;async function f(e,r=1){const n=`${L}?key=${w}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${v}`;try{return(await y.get(n)).data}catch(s){throw console.error("Error fetching the images:",s),s}}function P(e){e.innerHTML=""}function m(e,r){const n=e.map(t=>`
        <a href="${t.largeImageURL}" class="gallery__item">
            <img src="${t.webformatURL}" alt="${t.tags}" class="gallery__image" />
            <div class="info">
                <p class="info-item"><b>Likes:</b> ${t.likes}</p>
                <p class="info-item"><b>Views:</b> ${t.views}</p>
                <p class="info-item"><b>Comments:</b> ${t.comments}</p>
                <p class="info-item"><b>Downloads:</b> ${t.downloads}</p>
            </div>
        </a>
    `).join("");r.insertAdjacentHTML("beforeend",n),new p(".gallery a").refresh()}function i(e,r){b[e]({title:e.charAt(0).toUpperCase()+e.slice(1),message:r})}function d(e){document.querySelector(".load-more").classList.toggle("hidden",!e)}function S(){const{height:e}=document.querySelector(".gallery__item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}const $=document.getElementById("searchForm"),E=document.getElementById("searchQuery"),c=document.getElementById("results"),I=document.querySelector(".load-more");let a=1,h="";$.addEventListener("submit",async e=>{e.preventDefault();const r=E.value.trim();if(!r){i("error","Search query cannot be empty");return}h=r,a=1,P(c),d(!1),g();try{const{hits:n,totalHits:s}=await f(r,a);l(),n.length>0?(m(n,c),d(a*15<s)):i("info","Sorry, there are no images matching your search query. Please try again!")}catch{l(),i("error","Something went wrong. Please try again later.")}});I.addEventListener("click",async()=>{a++,g();try{const{hits:e,totalHits:r}=await f(h,a);l(),e.length>0&&(m(e,c),S(),d(a*15<r)),a*15>=r&&i("info","We're sorry, but you've reached the end of search results.")}catch{l(),i("error","Something went wrong. Please try again later.")}});function g(){c.insertAdjacentHTML("beforeend",'<div class="loader"></div>')}function l(){const e=document.querySelector(".loader");e&&e.remove()}
//# sourceMappingURL=commonHelpers.js.map
